name: VieMIUI ChinaBuild(TestPatch)

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: 'Input URL Direct Link Of ROM'
        required: true

jobs:
  VieMIUI_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Clean All Junk,App
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true

   - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          root-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checking CodeCode
        uses: actions/checkout@main

      - name: Checking Auth
        run: |
          
          git clone https://${{ secrets.PRIVATEP_TOKEN }}@github.com/hma1984/viemiui_erofs.git

      - name: Set up Time
        run: |
          echo "Setting Vienam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: Install Tool
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
          sudo apt-get update
          sudo apt-get install -y aria2 rclone sshpass wget python3 libc6 libstdc++6 python3-pip default-jdk 7zip dialog libgtk-3-dev aapt busybox zip unzip p7zip-full zipalign zstd bc android-sdk-libsparse-utils xmlstarlet
          sudo pip3 install ConfigObj
          
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          
      - name: VieMIUI Status
        env:
          INPUT_URL: ${{ inputs.input_url }}
        run: |
          cd viemiui_erofs
          ./startcn.sh "$INPUT_URL"
      
